---
- name: Create entries in /etc/hosts for all nodes
  blockinfile:
    path: /etc/hosts
    create: no
    state: present
    block: |
      {% for host in ansible_play_hosts %}{{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}.novalocal {{ host }}
      {% endfor %}
