---
- name: Generate /etc/hosts file content
  set_fact:
    etc_hosts_content: |
      {% for host in ansible_play_hosts %}
      {% if hostvars[host]['infra_intranet_interface'] is defined %}{{ hostvars[host][hostvars[host]['infra_intranet_interface']]['ipv4']['address'] }}{% else %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}{% endif %} {{ host }}.novalocal {{ host }}
      {% endfor %}
  run_once: true

- name: Create entries in /etc/hosts for all nodes
  blockinfile:
    path: /etc/hosts
    create: no
    state: present
    block: "{{ hostvars[ansible_play_hosts[0]].etc_hosts_content }}"

- name: Update hostname
  hostname:
    name: "{{ inventory_hostname }}.novalocal" 
  become: yes
  # FIXME
  ignore_errors: yes
