#!/bin/bash
openstack server reboot --hard euclid-ral_compute_0
openstack server reboot --hard euclid-ral_compute_1
openstack server reboot --hard euclid-ral_compute_2
openstack server reboot --hard euclid-ral_compute_3
openstack server reboot --hard euclid-ral_compute_4
openstack server reboot --hard euclid-ral_compute_5
openstack server reboot --hard euclid-ral_compute_6
openstack server reboot --hard euclid-ral_compute_7
openstack server reboot --hard euclid-ral_compute_8
openstack server reboot --hard euclid-ral_compute_9
openstack server reboot --hard euclid-ral_compute_10
openstack server reboot --hard euclid-ral_compute_11
openstack server reboot --hard euclid-ral_compute_12
openstack server reboot --hard euclid-ral_compute_13
openstack server reboot --hard euclid-ral_compute_14
openstack server reboot --hard euclid-ral_compute_15
openstack server reboot --hard euclid-ral_compute_16
openstack server reboot --hard euclid-ral_compute_17
openstack server reboot --hard euclid-ral_compute_18
openstack server reboot --hard euclid-ral_compute_19
openstack server reboot --hard euclid-ral_compute_20
openstack server reboot --hard euclid-ral_compute_21
openstack server reboot --hard euclid-ral_compute_22
openstack server reboot --hard euclid-ral_compute_23
openstack server reboot --hard euclid-ral_compute_24
openstack server reboot --hard euclid-ral_compute_25
openstack server reboot --hard euclid-ral_compute_26
openstack server reboot --hard euclid-ral_compute_27
openstack server reboot --hard euclid-ral_compute_28
openstack server reboot --hard euclid-ral_compute_29
openstack server reboot --hard euclid-ral_compute_30
openstack server reboot --hard euclid-ral_compute_31
openstack server reboot --hard euclid-ral_compute_32
openstack server reboot --hard euclid-ral_compute_33
openstack server reboot --hard euclid-ral_compute_34
openstack server reboot --hard euclid-ral_compute_35
openstack server reboot --hard euclid-ral_compute_36
openstack server reboot --hard euclid-ral_compute_37
openstack server reboot --hard euclid-ral_compute_38
openstack server reboot --hard euclid-ral_compute_39
openstack server reboot --hard euclid-ral_compute_40
openstack server reboot --hard euclid-ral_compute_41
openstack server reboot --hard euclid-ral_compute_42
openstack server reboot --hard euclid-ral_compute_43
openstack server reboot --hard euclid-ral_compute_44
openstack server reboot --hard euclid-ral_compute_45
openstack server reboot --hard euclid-ral_compute_46
openstack server reboot --hard euclid-ral_compute_47
openstack server reboot --hard euclid-ral_compute_48
openstack server reboot --hard euclid-ral_compute_49
openstack server reboot --hard euclid-ral_compute_50
openstack server reboot --hard euclid-ral_compute_51
openstack server reboot --hard euclid-ral_compute_52
openstack server reboot --hard euclid-ral_compute_53
openstack server reboot --hard euclid-ral_compute_54
openstack server reboot --hard euclid-ral_compute_55
openstack server reboot --hard euclid-ral_compute_56
openstack server reboot --hard euclid-ral_compute_57
openstack server reboot --hard euclid-ral_compute_58
openstack server reboot --hard euclid-ral_compute_59
openstack server reboot --hard euclid-ral_compute_60
openstack server reboot --hard euclid-ral_compute_61
openstack server reboot --hard euclid-ral_compute_62
openstack server reboot --hard euclid-ral_compute_63
openstack server reboot --hard euclid-ral_compute_64
openstack server reboot --hard euclid-ral_compute_65
openstack server reboot --hard euclid-ral_compute_66
openstack server reboot --hard euclid-ral_compute_67
openstack server reboot --hard euclid-ral_compute_68
openstack server reboot --hard euclid-ral_compute_69
openstack server reboot --hard euclid-ral_compute_70
openstack server reboot --hard euclid-ral_compute_71
openstack server reboot --hard euclid-ral_compute_72
openstack server reboot --hard euclid-ral_compute_73
openstack server reboot --hard euclid-ral_compute_74
openstack server reboot --hard euclid-ral_compute_75
openstack server reboot --hard euclid-ral_compute_76
openstack server reboot --hard euclid-ral_compute_77
openstack server reboot --hard euclid-ral_compute_78
openstack server reboot --hard euclid-ral_compute_79
openstack server reboot --hard euclid-ral_compute_80
openstack server reboot --hard euclid-ral_compute_81
openstack server reboot --hard euclid-ral_compute_82
openstack server reboot --hard euclid-ral_compute_83
openstack server reboot --hard euclid-ral_compute_84
openstack server reboot --hard euclid-ral_compute_85
openstack server reboot --hard euclid-ral_compute_86
openstack server reboot --hard euclid-ral_compute_87
openstack server reboot --hard euclid-ral_compute_88
openstack server reboot --hard euclid-ral_compute_89
