#!/bin/bah
openstack server reboot --hard euclid-cam-compute-0
openstack server reboot --hard euclid-cam-compute-1
openstack server reboot --hard euclid-cam-compute-2
openstack server reboot --hard euclid-cam-compute-3
openstack server reboot --hard euclid-cam-compute-4
openstack server reboot --hard euclid-cam-compute-5
openstack server reboot --hard euclid-cam-compute-6
openstack server reboot --hard euclid-cam-compute-7
openstack server reboot --hard euclid-cam-compute-8
openstack server reboot --hard euclid-cam-compute-9
openstack server reboot --hard euclid-cam-compute-10
openstack server reboot --hard euclid-cam-compute-11
openstack server reboot --hard euclid-cam-compute-12
openstack server reboot --hard euclid-cam-compute-13
openstack server reboot --hard euclid-cam-compute-14
openstack server reboot --hard euclid-cam-compute-15
openstack server reboot --hard euclid-cam-compute-16
openstack server reboot --hard euclid-cam-compute-17
openstack server reboot --hard euclid-cam-compute-18
openstack server reboot --hard euclid-cam-compute-19
openstack server reboot --hard euclid-cam-compute-20
openstack server reboot --hard euclid-cam-compute-21
openstack server reboot --hard euclid-cam-compute-22
openstack server reboot --hard euclid-cam-compute-23
openstack server reboot --hard euclid-cam-compute-24
openstack server reboot --hard euclid-cam-compute-25
openstack server reboot --hard euclid-cam-compute-26
openstack server reboot --hard euclid-cam-compute-27
openstack server reboot --hard euclid-cam-compute-28
openstack server reboot --hard euclid-cam-compute-29
openstack server reboot --hard euclid-cam-compute-30
openstack server reboot --hard euclid-cam-compute-31
openstack server reboot --hard euclid-cam-compute-32
openstack server reboot --hard euclid-cam-compute-33
openstack server reboot --hard euclid-cam-compute-34
openstack server reboot --hard euclid-cam-compute-35
