---
- name: Restart NetworkManager service
  systemd:
    name: NetworkManager
    enabled: True
    state: restarted
  become: True

- name: Reset interface
  shell: ifdown ib0; ifup ib0
  become: yes
...
