---
# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
cluster_name: euclid2

squid_package: "squid"
squid_service: "squid"

cluster_groups:
  - "{{ openvpn_gw }}"
  - "{{ slurm_login }}"
  - "{{ slurm_control }}"
  - "{{ slurm_compute }}"
  - "{{ cvmfs_proxy }}"

cluster_gw_group: "gw"

openvpn_gw:
  name: "gw"
  flavor: "m2.small"
  image: "ScientificLinux-7-NoGui"
  user: "stelfer"
  num_nodes: 1
  nodenet_resource: "Cluster::NodeNet1WithPreallocatedFIP"
  nodenet_fips:
    - uuid: "1eacdf5a-7681-4a9f-ae4e-c16474bc7717"
      ip: "130.246.215.191"

slurm_login:
  name: "login"
  flavor: "m2.medium"
  image: "ScientificLinux-7-NoGui"
  user: "stelfer"
  num_nodes: 1
  nodenet_resource: "Cluster::NodeNet1WithPreallocatedFIP"
  nodenet_fips:
    - uuid: "4996ee00-1ee3-4db3-ab28-ec8e5acbd256"
      ip: "130.246.215.152"

slurm_control:
  name: "control"
  flavor: "m2.medium"
  image: "ScientificLinux-7-NoGui"
  user: "stelfer"
  num_nodes: 1
  nodenet_resource: "Cluster::NodeNet1"

slurm_compute:
  name: "compute"
  flavor: "m2.large"
  image: "ScientificLinux-7-NoGui"
  user: "stelfer"
  num_nodes: 6
  nodenet_resource: "Cluster::NodeNet1"

cvmfs_proxy:
  name: "proxy"
  flavor: "m2.medium"
  image: "ScientificLinux-7-NoGui"
  user: "stelfer"
  num_nodes: 1
  nodenet_resource: "Cluster::NodeNet1"
  #node_resource: "Cluster::InstanceWithVolume"
  #volume_size: 60
  #volume_type: "rbd"


# Node group assignments for cluster roles.
# These group assignments are appended to the cluster inventory file.
# The names of these roles are cross-referenced to groups referred to
# in playbooks in the ansible/ directory.
cluster_roles:
  - name: "ceph_client"
    groups: 
      - "{{ slurm_login }}"
      - "{{ slurm_control }}"
      - "{{ slurm_compute }}"
  - name: "control"
    groups: 
      - "{{ slurm_control }}"
  - name: "login"
    groups: 
      - "{{ slurm_login }}"
  - name: "batch"
    groups: 
      - "{{ slurm_compute }}" 
  - name: "cvmfs_proxy"
    groups:
      - "{{ cvmfs_proxy }}"

# Define a list of SLURM partitions to create.
openhpc_slurm_partitions: 
  - name: ral
    groups:
      - "{{ slurm_compute }}"

# A list of OpenHPC runtime libraries to install on compute and control nodes
openhpc_packages:
  - strace
  - flex
  - bison
  - cfitsio
  - cfitsio-devel
  - cfitsio-docs
  - wcslib
  - wcslib-utils
  - wcslib-devel
  - wcstools
  - ncurses
  - ncurses-devel
  - readline
  - readline-devel
  - boost
  - boost-devel
  - boost-python
  - boost-math
  - boost-doc
  # OpenHPC bits
  - hdf5-gnu-ohpc
  - phdf5-gnu-mvapich2-ohpc
  - gnu-compilers-ohpc
  - mvapich2-gnu-ohpc
  - openmpi-gnu-ohpc
  - imb-gnu-mvapich2-ohpc
  - imb-gnu-openmpi-ohpc
  - fftw-gnu-mvapich2-ohpc
  - fftw-gnu-openmpi-ohpc
  - openblas-gnu-ohpc
  - scalapack-gnu-mvapich2-ohpc
  - gsl-gnu-ohpc
  - python-scipy-gnu-mvapich2-ohpc
  - python-scipy-gnu-openmpi-ohpc
  - python34
  - python34-devel
  - python-virtualenv
  - infiniband-diags
  - emacs
  - vim
  # EUCLID-specific software depencencies
  - eigen3-devel
  - eigen3-doc
  - healpix-c++
  - healpix-c++-devel
  - healpix
  - xerces-c-devel
  - xerces-c-doc
  - xerces-c
  - odb
  - libpng-devel
  - libpng
  - cairo
  - cairo-devel
  - python-matplotlib 
# - python-astropy
# - python-astropy-doc
  - PyQt4
  - PyQt4-devel
  - pyephem
  - python-Cython
  - python-Cython-debuginfo

#  - git-lfs

euclid_homedir: "/euclid"
euclid_group_name: "euclid"
iris_group_name: "iris"
euclid_groups:
  - name: "{{ euclid_group_name }}"
    gid: 2000
  - name: "{{ iris_group_name }}"
    gid: 8069


euclid_users:
  - username: "hpcgill1"
    groups: [ "{{ euclid_group_name }}", "{{ iris_group_name }}" ]
    name: "Bryan R. Gillis <b.gillis@roe.ac.uk>"
    home: "{{euclid_homedir}}/hpcgill1"
    uid: 16291
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDP81krWUzI5Oz/CQPMfHxzvJ2Z9mtSEXTvTgeZ73wqizqti5iO/1lskMX8eqiVSPJqRAc5iTbCgYsZ2fSxbharQOex8MR5e3BhMa3s8YPB6ACkUYsgY/qoASyP59HRlntQzLlzbrUz56eYarGf/6V9DiW0y43c/P6CujaoWOf0n69Vy+Qj7O7jI38PaKm0lUzpVA6QQjJmARxvqff7zt0hWJX548x0ReEXGfb86G18GOtBk3mZLb6IvNmqU2xFuUX5RaM7P2OBSU2KEkCVZ9rNQQL2CEOyTrmJUg92T556HaZna15E4Qt7ux4mGLgk+IB203efKiQ536Ftr/2ZRfOL brg@sdc-uk.roe.ac.uk"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhgvKgiWkXdl1ah+u7BnGrTB+46MmP7fEX89YpxsKeC3l9+av9wh1jPwJ3sxpmHFa6HKhyi8IR/UjP16FACaUkXMSxxcTD8fCMnk5lH47kwUeed9DNABCS2RYB9Fe3MQAfMJfqEUjLwrmbloS0/IsfbC4vlqcW2XYezQrYzArWC5b02i8sROe9Mcb+T6+loljMPYZy/yKY2e4lAryLZB4h8dYyBqulkhXx6EeKWdmPKj9TBqu1TLf6/P6OGvlQ2ZJmXJnRWAePZDTDy2aGvHHQDEyWrBVmF7sLnLF0na444zMSm+EyX8beu609yRiSktELrONqgtqD3HmXLJqhjA0b hpcgill1@ilab-gate.ilab.cluster"
#  - username: "hpccong1"
#    groups: [ "{{ euclid_group_name }}", "{{ iris_group_name }}" ]
#    name: "Giuseppe Congedo <giuseppe.congedo@ed.ac.uk>"
#    home: "{{euclid_homedir}}/hpccong1"
#    uid: 2002
#    ssh_key:
#      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQharjXndGvQLihlPp9tdXzSUNei/JUFuiOJbkfdNoPUAM+ZrV+LhI6HEGD7jJxDom86FK/f4QveZi/Xk+g1dfSQvtIj0YGJyu+5GZPkJfpxQsDwcIaaH96yqJMe9Xbh8asnoqkAGZIi7+QUaffEhOcuy9cajgfBwx81tav56rRNl8R6ej9c3nauAdMM1A+Nd98sKNk9VPM1m+6SKEbmHLL6AQTIRZMNz8r5PzPAqmkoDTx2nXnqVSsVi4TZ0RU4meIKhCzqZLGKUEqFKVhNmAmNLmGkI2IhAF+qTjR7Y+jHW/pyj/rZ0CU+B0tpJ7OaUQ6P14HdUeRbSXHR7TXkxT gconge@sdc-uk.roe.ac.uk"
  - username: "hpcholl1"
    groups: [ "{{ euclid_group_name }}", "{{ iris_group_name }}" ]
    name: "Mark Holliman <msh@roe.ac.uk>"
    home: "{{euclid_homedir}}/hpcholl1"
    uid: 16287
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwNcXawcsNzA73TxmyozskeA3Ex5el0iLhGWtSPz43R5//VjE/7sHmcsrm8HsFnDXp35S+GIwSX3MwGkjzzrUOCz2yGZi82yq9AzhYS1fa1UJhYb76HevIMk85u3DNij4FuNFnTCmoVWXglukrCHW8KgsqBiuah9uXZfsRPOysJOjWLcj+VI+U5A4kVehpyFNMAi5Re4/9n/PSxbvcNmsdW6lpEVhHJcYDmKPd6ZvgiH2uf6kpeTffb2LQAdittchhKot+0AAe5nERVcCGd8NGYcApf0pJ7KJU7xzzliBAZbYvEsnJTuJDfInVLFIZPHZdJGyv7VyqNNqW9WoXg1Cr euclid@sdc-uk.roe.ac.uk"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWnl+U7SsHd+BggD498vGl7sOOF6cP5bo1QJsBHQsBdgsmcrutb2ZzHgW5/jCiR8DUtj+ezN0NnIQPkcPBNsMCKYx0ib+mE9SlPVru3uqWp9oK/Bl6FWwWdG2KIX7tlbWAKlb2toHXD6C9mV88g2oiaYI7576MGbDjUHGlxPoP3JT78TpUeJ1UOPoQ5gXo/39Y8qzfSKoPvibP0CuDCLB/7nob8LYaFaHczTILcrfhnrDNMg5WjhaDoMobjWwTAAe7x+YRbPsmYAESax8CsjvRjiJkQ7Z8XkBd3hCuQqTeaegtNAxfIimYs0oPhYMk7dZaT5ZoG/AB1TlmUO1oGIyv hpcholl1@ilab-gate.ilab.cluster"
  - username: "hpccros1"
    groups: [ "{{ euclid_group_name }}", "{{ iris_group_name }}" ]
    name: "Nick Cross <njc@roe.ac.uk>"
    home: "{{euclid_homedir}}/hpccros1"
    uid: 16290
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDT9nHQ7Z+2Kql2CI6koEbgDWlYy7LzSiI4tGlDoa6p30EuwZjiEZTtRLQhcT/ZTWN4KHocyIUohwnxwon/X0ETQxh/bOaWvEVwYEJ0ihRdTWZtDc6VF9ty8Tsq8tWm0q7dH5agr6wRND1tTVfHiSYA9L32h6SVP6HVZBPfSHQ626SWe0QenMwFFU47Ohv4j+KDz9aq0FLR6/Lp1gyl9X73WVmpjGUSpt4xAHMrIj3TGbT8vHIpsi9Vp3qxKFdzDGtsVbrUBppAUp8ZmdXpQVCFLhIuCP49j8ElZv+k9W89WQDytDNLo+zkNN5mNCnc5lNI3pldVjt1608bn0KzlflD njc@sdc-uk.roe.ac.uk"
#  - username: "hpcweli1"
#    groups: [ "{{ euclid_group_name }}", "{{ iris_group_name }}" ]
#    name: "Niraj Welikala <nirajw@roe.ac.uk>"
#    home: "{{euclid_homedir}}/hpcweli1"
#    uid: 2005
#    ssh_key:
#      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI8NVRUR6uro/ZTNQ8BPgy8+a3OSK47HKmP9zmmYhTyHcmRoZsnyVsmzXvMxtvMJsehWtA6l07yzdisShXemZqKQpdiJkw269ofo1eXKyA1Sw/C5wHGZSLE6bZkX1+rFeNlJII+CgxnVgyfQRVh1wnsrQJSKwGd7o+qOo3iYJiE9gGZChZdHFiUgZ7X9IJz21R7/Ra4h+COpXMC4sNVjyT7dswHi1Kjj1IYnKVnDaeOy7Ofgy96O6S5vz1uVrvUxhhyvoK3D4KQ5zoG3bW8wfAZjUXx3MXmMAV4SsnOXz5EWZA6wwMzvH1O177IwbScv8HmSsQfIRiQ8PlKMnMXABR nirajw@sdc-uk.roe.ac.uk"
  - username: "sclt100"
    name: "Stig Telfer <stig@stackhpc.com>"
    home: "{{euclid_homedir}}/sclt100"
    uid: 15238
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCLva2hRoqcA77XoK0t7aPmip4CmxM6SdsnJdbN4i0l72Rf6HMNH2ZR5p+eZPxaxiJgmtQ5MpquNt775lFSGVIV7oyAKDdYuLA/8KXoKje4EsCMfA9m6Eg8urjrPprelTAl7xsem1eH9c/Jk6TFbJSyMrY7kvgNo1KZ+D24F5cCSSRncy0s5GoPWEJfdnSHdjvxc97vhSPY9KwsaMdbpj+u+1WlUDeoLjMsWLPDsqnIHLwYN74f9jfTvsoQxw9Wq3dmzRvy8sQkJ1OoAeuuM4B4MKel7U6QqrhMYyIUG2pcSBBICtT2Q5V4RhnBIqQrL8w1efq+TeD/ETSuQgFBiq1 sclt100@ilab-gate.ilab.cluster"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqySju7sKVGV8muTQ3KL7ZN/b4FQ3Sbm3vuUMEjO7lShmb7QeeXcQnJLkqiUD+VOC7WtBDwlMtvtC9KQHixpBohBrV/0fJ4zBElQ5ijpnLmwmKN/lEcoquvpL37LVAH7PxpnY2ElhhdgJxxYqruhJJZSwxTYC3XGoY1YosYY5SqZM1ZpTfEVHuN7VCzCiggcDHJAd+zG+1XRlYUHqPB3f29ymXTSG1C3EwaezrTY6+nUM5+Kcw7bOutxPfSev5Vk9densyQg9tsfjWBC0fbobOltWsycDMvlhT/Otc8XMFaHw1BZKjVkrcDQ2t364h9RmLGs6k777ECiE1IphSbXST sclt100@eod-control"
  - username: "pfb29"
    name: "Paul Browne <pfb29@cam.ac.uk>"
    home: "{{euclid_homedir}}/pfb29"
    uid: 15080
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4gcLMvI8rOXZsuIAp2Dza2TalJGQyRzvYl0kQKBxeNNu700wn3aFoZA7AXexN/3wIhXZbueXEX+rlXKQRPm2pGHqKBhaAM1k9+vol5kYtMeSLBR5zVdUxpOCcBZeObCjNdk6Ul2JacETSd56/Dr/rjuaPe8uGeC0THz9Om55qwgpY0meTaptE3FezX8juZiSV9afH1G/ktOCA/G0xTaxUOAOzZXJLtbmqPWdPQ//1p+60pOLJBVkiwERcoWspcWem236hNrb1xtItbxYGalZXqUaDUpXsh5E4QrJGIh4J3hXQ8sVelDXx+RSiOl867xv/LkAPs8iZ0oSVCXrTIrhz pfb29"

# Manila config
ceph_mount_share_name: "euclid"
ceph_mount_share_user: "euclid"
manila_mount_point: "{{ euclid_homedir }}"

cvmfs_conf_local: |
  CVMFS_REPOSITORIES=euclid.in2p3.fr,euclid-dev.in2p3.fr
  CVMFS_HTTP_PROXY="http://euclid-proxy-0:3128"

# FIXME: The following nodes from the PoC rack do not have access to IB
# currently.
no_ib_connectivity:
  - euc-bare-9
  - euc-bare-92
  - euc-bare-298

# The login node is running on a repurposed bare metal compute node.
slurm_login_node_with_ib: euc-2-bare-43

slurm_service_enabled: "{{ inventory_hostname not in (no_ib_connectivity + [slurm_login_node_with_ib]) }}"
