---
cluster_name: orange
cluster_keypair: ilab_sclt100
cluster_groups:
  - "{{ orangefs_meta }}"
  - "{{ orangefs_data }}"
  - "{{ orangefs_client }}"

orangefs_meta:
  name: "meta"
  flavor: "storage-A"
  image: "FedoraCore"
  user: "fedora"
  num_nodes: 1
  user: "fedora"

orangefs_data:
  name: "data"
  flavor: "storage-B"
  image: "FedoraCore"
  user: "fedora"
  num_nodes: 2
  user: "fedora"

orangefs_client:
  name: "client"
  flavor: "compute-A"
  image: "FedoraCore"
  user: "fedora"
  num_nodes: 4
  user: "fedora"

