
- hosts:
    - euclid-cam_compute
  become: yes
  tasks:
    - name: Ensure vdb is not mounted on /mnt
      mount:
        src: "{{ compute_ephemeral_dev }}"
        path: "/mnt"
        state: absent

