# Gather data on RAM resource per flavor in use
# A dict called flavor_ram is returned by this play
#- hosts: openstack
#  tasks:
#    - include_tasks: flavor_ram.yml
#      with_items: "{{ cluster_groups | map(attribute='flavor') | unique | list }}"

# Generate a dict mapping slurm partition to the minimum physical ram 
# available for members of that partition
# we have a group
- hosts: 
    - slurm_compute_bare

- hosts:
    - cluster_control
    - cluster_login
    - cluster_batch
  become: yes
  pre_tasks:
    - name: Ensure the OpenHPC package repo rpm is present
      yum:
        name: "https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm"
        state: present
      become: yes
    # In the images used in RAL, a GID wanted by Munge (201) is already
    # claimed by NAGIOS.
    - name: Purge site NAGIOS plugins and POSIX groups
      block:
        - yum:
            name:
              - nagios-plugins-load
              - nagios-plugins-swap
              - nagios-plugins
              - nagios-plugins-perl
              - nagios-plugins-ntp
              - nagios-plugins-procs
              - nagios-common
              - nagios-plugins-disk
              - nagios-plugins-ping
              - nagios-plugins-log
              - nagios-plugins-icmp
              - nagios-plugins-nrpe
              - tier1-nagios-plugins
            state: absent
        - user:
            name: nagios
            state: absent 
        - group:
            name: nagios
            state: absent 
      become: yes
    - name: Bodge to ensure latest python is present
      yum:
        name: python
        state: latest

- include: slurm.yml
  slurm_partitions: "{{ openhpc_slurm_partitions }}"
  slurm_control_host: "{{ groups['cluster_control'] | first }}"
