# Gather data on RAM resource per flavor in use
# A dict called flavor_ram is returned by this play
#- hosts: openstack
#  tasks:
#    - include_tasks: flavor_ram.yml
#      with_items: "{{ cluster_groups | map(attribute='flavor') | unique | list }}"

# Generate a dict mapping slurm partition to the minimum physical ram 
# available for members of that partition
# we have a group
- hosts: 
    - slurm_compute_bare

- hosts:
    - cluster_control
    - cluster_login
    - cluster_batch
  become: yes
  tasks:
    - name: Ensure the OpenHPC package repo rpm is present
      yum:
        name: "https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm"
        state: present
      become: yes

    - name: Ensure latest python is present
      yum:
        name: python
        state: latest

    # Configure parameters for Slurm playbook
    - set_fact:
        slurm_partitions: "{{ openhpc_slurm_partitions }}"
        slurm_control_host: "{{ groups['cluster_control'] | first }}"

# Run the common slurm playbook, pulling in facts defined above
- import_playbook: slurm.yml
