---
# Query OpenStack Barbican to retrieve secret keys
# needed for a cluster deployment
#- hosts: openstack
#  roles:
#    - role: alaska_secrets
#      secret_name: "alaska.auth.p3-monitor"
#      secret_var: "alaska_auth_p3_monitor"
  
# Apply generic setup configuration that is universally useful
- hosts: cluster
  become: yes
  tasks:
    - command: "yum-config-manager --disable OpenHPC-updates"
    - command: "yum-config-manager --disable openstack-queens"

