# Example usage:
# ansible-playbook -i ansible/inventory-openhpc --vault-password-file=vault-password -e src="10.3.0.27:/openhpc_vol" -e path="/mnt/gluster" -e state="mounted" -e fstype="glusterfs" ansible/mount.yml
# ansible-playbook -i ansible/inventory-openhpc --vault-password-file=vault-password -e path="/mnt/gluster" -e state="unmounted" ansible/mount.yml
- hosts: cluster
  gather_facts: yes
  tasks:
  - name: Mount given path
    mount:
      src: "{{ src | default(omit) }}"
      path: "{{ path }}"
      fstype: "{{ fstype | default(omit) }}"
      state: "{{ state | default('present') }}"
      opts: "{{ opts | default(omit) }}"
    become: yes
