---
# Query OpenStack Barbican to retrieve secret keys
# needed for a cluster deployment
#- hosts: openstack
#  roles:
#    - role: alaska_secrets
#      secret_name: "alaska.auth.p3-monitor"
#      secret_var: "alaska_auth_p3_monitor"
  
# Apply generic setup configuration that is universally useful
- hosts: cluster
  become: yes
  roles:
    - role: oasis_roles.kdump
      kdump_package: kexec-tools
      kdump_conf_path: /etc/kdump.conf
      kdump_become_user: root
      kdump_crash_path: /var/crash
      kdump_core_collector_args: makedumpfile -l --message-level 1 -d 31
      when: kdump_enable | default(true)

    - role: cluster_setup

    - role: resmo.ntp
      ntp_config_server: "{{ infra_ntp_servers | default(omit) }}"

  tasks:

    # Improve entropy for processors with hardware support for rdrand
    # This improves the performance of encrypted connections
    - name: Ensure RNGD package is installed
      package:
        name: rng-tools
        state: present
    - name: Ensure RNGD is enabled and started
      systemd:
        name: rngd
        enabled: yes
        state: started


# Bring in site-specific infrastructure configuration.
# It doesn't seem like there's a parameterised way of doing this
- import_playbook: "setup-edi.yml"
  when: infra_name == "edi"
- import_playbook: "setup-ral.yml"
  when: infra_name == "ral"
- import_playbook: "setup-cam.yml"
  when: infra_name == "cam"
- import_playbook: "setup-sausage.yml"
  when: infra_name == "sausage"

# Nodes that are defined as OSD servers must have LVM configuration applied.
# This configuration will be defined in site inventory.
- hosts: cluster_ceph_osd
  roles:
    - role: mrlesmithjr.manage-lvm
      become: true
...
