---

# Site configuration specific to RAL OpenStack infrastructure.

- hosts:
    - euclid_sausage

  become: yes

  roles:
    - role: stackhpc.cluster-nfs
      nfs_enable:
        server: "{{ inventory_hostname in groups['euclid_sausage_control'] }}"
        clients: "{{ inventory_hostname in groups['euclid_sausage_login']|union(groups['euclid_sausage_compute'])}}"
      nfs_export: "/srv/euclid"
      nfs_client_mnt_point: "{{ euclid_homedir }}"
      nfs_server: "{{ groups['euclid_sausage_control'] | first }}"

...
