---

# Site configuration specific to RAL OpenStack infrastructure.

# Create some fake OSD storage devices on compute nodes
- hosts:
    - euclid-sausage_compute

  become: yes

  tasks:
    - name: Create loopback backing file
      command: "dd if=/dev/zero of={{ sausage_osd_loopback_file }} bs=1G count={{ sausage_osd_loopback_gigabytes }}"
      args:
        creates: "{{ sausage_osd_loopback_file }}"

    - name: Create loopback device
      command: "losetup /dev/loop0 {{ sausage_osd_loopback_file }}"
      args:
        creates: "/dev/loop0"

...
